language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      dotnet: 1.0.4
      mono: none
    - os: osx
      osx_image: xcode7.3
      dotnet: 1.0.4
      mono: none

branches:
  only:
  - master

# Work around NuGet issue #2163
# Too many files open error
# https://github.com/NuGet/Home/issues/2163
# https://github.com/travis-ci/travis-ci/issues/7728
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ulimit -n 1024; fi

install:
  - dotnet restore NTumbleBit.sln
script:
  - dotnet build NTumbleBit.sln
 # - dotnet build -c Release -f netcoreapp1.1 ./NTumbleBit.Tests/NTumbleBit.Tests.csproj
